'use client'

import { useState, useEffect } from 'react'
import { useRouter } from 'next/navigation'
import AdminLayout from '@/components/ui/AdminLayout'
import { withAuth, useAuth } from '@/contexts/AuthContext'
import {
  Calendar,
  TrendingUp,
  Clock,
  AlertTriangle,
  CheckCircle,
  RefreshCw,
  BarChart3,
  RotateCcw,
  Users
} from 'lucide-react'

interface WeeklyTaskSummary {
  user_id: string
  user_name: string
  week_start: string
  week_end: string
  total_tasks: number
  completed_tasks: number
  in_progress_tasks: number
  pending_tasks: number
  completion_rate: number
  self_tasks: number
  subsidy_tasks: number
  high_priority_completed: number
  medium_priority_completed: number
  low_priority_completed: number
  completed_task_details: Array<{
    id: string
    title: string
    business_name: string
    task_type: string
    status: string
    completed_at: string
    priority: string
  }>
  pending_task_details: Array<{
    id: string
    title: string
    business_name: string
    task_type: string
    status: string
    due_date?: string
    priority: string
    days_overdue?: number
  }>
  average_completion_time_days: number
  overdue_tasks: number
  created_at: string
}

function WeeklyReportsPage() {
  const { user } = useAuth()
  const router = useRouter()
  const [report, setReport] = useState<WeeklyTaskSummary | null>(null)
  const [loading, setLoading] = useState(false)
  const [selectedWeek, setSelectedWeek] = useState('')
  const [dataSource, setDataSource] = useState<'database' | 'generated' | null>(null)
  const [isAutoGenerated, setIsAutoGenerated] = useState(false)
  const currentUserId = user?.id || '' // Auth context에서 사용자 ID 가져옴
  const isAdmin = (user?.permissionLevel || 0) >= 3 // 관리자 권한 확인

  // 이번 주 날짜를 기본값으로 설정
  useEffect(() => {
    const today = new Date()
    const monday = new Date(today.setDate(today.getDate() - today.getDay() + 1))
    setSelectedWeek(monday.toISOString().split('T')[0])
  }, [])

  const fetchWeeklyReport = async (forceRegenerate = false) => {
    if (!selectedWeek) return

    setLoading(true)
    try {
      const url = `/api/weekly-reports?userId=${currentUserId}&weekDate=${selectedWeek}${forceRegenerate ? '&forceRegenerate=true' : ''}`
      const response = await fetch(url)
      const data = await response.json()

      if (data.success) {
        setReport(data.data.report)
        setDataSource(data.data.summary?.data_source || null)
        setIsAutoGenerated(data.data.summary?.is_auto_generated || false)

        if (forceRegenerate) {
          alert('리포트가 재생성되었습니다.')
        }
      } else {
        console.error('주간 리포트 조회 실패:', data.error)
        alert('리포트 조회에 실패했습니다.')
      }
    } catch (error) {
      console.error('주간 리포트 조회 오류:', error)
      alert('리포트 조회 중 오류가 발생했습니다.')
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    if (selectedWeek) {
      fetchWeeklyReport()
    }
  }, [selectedWeek])

  const formatDate = (dateStr: string) => {
    return new Date(dateStr).toLocaleDateString('ko-KR', {
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    })
  }

  const getStatusBadgeColor = (status: string) => {
    switch (status) {
      case 'document_complete':
      case 'subsidy_payment':
      case 'final_document_submit':
        return 'bg-green-100 text-green-800'
      case 'site_survey':
      case 'document_preparation':
      case 'subsidy_application':
        return 'bg-blue-100 text-blue-800'
      default:
        return 'bg-gray-100 text-gray-800'
    }
  }

  const getPriorityColor = (priority: string) => {
    switch (priority) {
      case 'high': return 'text-red-600'
      case 'medium': return 'text-yellow-600'
      case 'low': return 'text-green-600'
      default: return 'text-gray-600'
    }
  }

  return (
    <AdminLayout
      title="주간 업무 리포트"
      description="개인별 주간 업무 성과 및 진행 상황 분석"
    >
      <div className="space-y-6">
        {/* 관리자 링크 (권한 3 이상) */}
        {isAdmin && (
          <div className="bg-gradient-to-r from-purple-50 to-indigo-50 rounded-xl border border-purple-200 p-3 md:p-4">
            <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 bg-purple-100 rounded-lg flex items-center justify-center flex-shrink-0">
                  <Users className="w-5 h-5 text-purple-600" />
                </div>
                <div>
                  <h3 className="font-semibold text-gray-900 text-sm md:text-base">관리자 기능</h3>
                  <p className="text-xs md:text-sm text-gray-600">전체 사용자의 주간 리포트를 확인하세요</p>
                </div>
              </div>
              <button
                onClick={() => router.push('/admin/weekly-reports/admin')}
                className="w-full sm:w-auto flex items-center justify-center gap-2 px-3 md:px-4 py-2 text-sm bg-purple-600 text-white rounded-lg hover:bg-purple-700 transition-colors"
              >
                <Users className="w-4 h-4" />
                <span className="hidden sm:inline">전체 리포트 관리</span>
                <span className="sm:hidden">전체 리포트</span>
              </button>
            </div>
          </div>
        )}

        {/* 컨트롤 영역 */}
        <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-3 md:p-6">
          <div className="flex flex-col gap-3 md:gap-4">
            <div className="flex flex-col sm:flex-row gap-3 items-start sm:items-center">
              <div className="flex items-center gap-2">
                <Calendar className="w-4 h-4 md:w-5 md:h-5 text-gray-500" />
                <label className="text-xs md:text-sm font-medium text-gray-700">주간 선택:</label>
              </div>
              <input
                type="date"
                value={selectedWeek}
                onChange={(e) => setSelectedWeek(e.target.value)}
                className="w-full sm:w-auto px-3 py-2 border border-gray-300 rounded-lg text-sm focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              />
            </div>
            <div className="flex flex-col sm:flex-row gap-2 items-stretch sm:items-center">
              <button
                onClick={() => fetchWeeklyReport(false)}
                disabled={loading}
                className="flex items-center justify-center gap-2 px-3 md:px-4 py-2 text-sm bg-blue-600 text-white rounded-lg hover:bg-blue-700 disabled:opacity-50 transition-colors"
              >
                <RefreshCw className={`w-4 h-4 ${loading ? 'animate-spin' : ''}`} />
                <span className="hidden sm:inline">{loading ? '조회중...' : '리포트 조회'}</span>
                <span className="sm:hidden">{loading ? '조회중...' : '조회'}</span>
              </button>
              {report && (
                <button
                  onClick={() => fetchWeeklyReport(true)}
                  disabled={loading}
                  className="flex items-center justify-center gap-2 px-3 md:px-4 py-2 text-sm bg-gray-600 text-white rounded-lg hover:bg-gray-700 disabled:opacity-50 transition-colors"
                >
                  <RotateCcw className="w-4 h-4" />
                  재생성
                </button>
              )}
              {dataSource && (
                <span className={`px-3 py-1 text-xs md:text-sm rounded-full ${
                  dataSource === 'database' ? 'bg-green-100 text-green-800' : 'bg-blue-100 text-blue-800'
                }`}>
                  {dataSource === 'database' ? (
                    <>💾 저장됨{isAutoGenerated && ' (자동)'}</>
                  ) : (
                    '🔄 실시간'
                  )}
                </span>
              )}
            </div>
          </div>
        </div>

        {/* 리포트 내용 */}
        {report ? (
          <div className="space-y-6">
            {/* 리포트 헤더 */}
            <div className="bg-gradient-to-r from-blue-50 to-indigo-50 rounded-xl border border-blue-200 p-4 md:p-6">
              <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3">
                <div className="flex-1">
                  <h2 className="text-lg md:text-2xl font-bold text-gray-900">{report.user_name}님의 주간 리포트</h2>
                  <p className="text-xs md:text-base text-gray-600 mt-1">
                    {formatDate(report.week_start)} - {formatDate(report.week_end)}
                  </p>
                </div>
                <div className="flex sm:flex-col items-center sm:items-end gap-2 sm:gap-0">
                  <div className="text-2xl md:text-3xl font-bold text-blue-600">{report.completion_rate}%</div>
                  <div className="text-xs md:text-sm text-gray-600">완료율</div>
                </div>
              </div>
            </div>

            {/* 통계 카드 */}
            <div className="grid grid-cols-2 md:grid-cols-2 lg:grid-cols-4 gap-3 md:gap-6">
              <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-3 md:p-6">
                <div className="flex items-center gap-2 md:gap-3">
                  <div className="w-10 h-10 md:w-12 md:h-12 bg-blue-100 rounded-lg flex items-center justify-center flex-shrink-0">
                    <BarChart3 className="w-5 h-5 md:w-6 md:h-6 text-blue-600" />
                  </div>
                  <div>
                    <div className="text-lg md:text-2xl font-bold text-gray-900">{report.total_tasks}</div>
                    <div className="text-xs md:text-sm text-gray-600">총 업무</div>
                  </div>
                </div>
              </div>

              <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-3 md:p-6">
                <div className="flex items-center gap-2 md:gap-3">
                  <div className="w-10 h-10 md:w-12 md:h-12 bg-green-100 rounded-lg flex items-center justify-center flex-shrink-0">
                    <CheckCircle className="w-5 h-5 md:w-6 md:h-6 text-green-600" />
                  </div>
                  <div>
                    <div className="text-lg md:text-2xl font-bold text-gray-900">{report.completed_tasks}</div>
                    <div className="text-xs md:text-sm text-gray-600">완료</div>
                  </div>
                </div>
              </div>

              <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-3 md:p-6">
                <div className="flex items-center gap-2 md:gap-3">
                  <div className="w-10 h-10 md:w-12 md:h-12 bg-yellow-100 rounded-lg flex items-center justify-center flex-shrink-0">
                    <Clock className="w-5 h-5 md:w-6 md:h-6 text-yellow-600" />
                  </div>
                  <div>
                    <div className="text-lg md:text-2xl font-bold text-gray-900">{report.average_completion_time_days}일</div>
                    <div className="text-xs md:text-sm text-gray-600">평균 완료</div>
                  </div>
                </div>
              </div>

              <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-3 md:p-6">
                <div className="flex items-center gap-2 md:gap-3">
                  <div className="w-10 h-10 md:w-12 md:h-12 bg-red-100 rounded-lg flex items-center justify-center flex-shrink-0">
                    <AlertTriangle className="w-5 h-5 md:w-6 md:h-6 text-red-600" />
                  </div>
                  <div>
                    <div className="text-lg md:text-2xl font-bold text-gray-900">{report.overdue_tasks}</div>
                    <div className="text-xs md:text-sm text-gray-600">연체</div>
                  </div>
                </div>
              </div>
            </div>

            {/* 진행 상황 차트 */}
            <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-4 md:p-6">
              <h3 className="text-base md:text-lg font-semibold text-gray-900 mb-3 md:mb-4">업무 진행 현황</h3>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4 md:gap-6">
                {/* 상태별 분포 */}
                <div>
                  <h4 className="text-xs md:text-sm font-medium text-gray-700 mb-2 md:mb-3">상태별 분포</h4>
                  <div className="space-y-2 md:space-y-3">
                    <div className="flex items-center justify-between gap-2">
                      <span className="text-xs md:text-sm text-gray-600 whitespace-nowrap">완료</span>
                      <div className="flex items-center gap-2 flex-1">
                        <div className="flex-1 bg-gray-200 rounded-full h-2">
                          <div
                            className="bg-green-600 h-2 rounded-full"
                            style={{ width: `${(report.completed_tasks / report.total_tasks) * 100}%` }}
                          />
                        </div>
                        <span className="text-xs md:text-sm font-medium w-6 text-right">{report.completed_tasks}</span>
                      </div>
                    </div>
                    <div className="flex items-center justify-between gap-2">
                      <span className="text-xs md:text-sm text-gray-600 whitespace-nowrap">진행중</span>
                      <div className="flex items-center gap-2 flex-1">
                        <div className="flex-1 bg-gray-200 rounded-full h-2">
                          <div
                            className="bg-blue-600 h-2 rounded-full"
                            style={{ width: `${(report.in_progress_tasks / report.total_tasks) * 100}%` }}
                          />
                        </div>
                        <span className="text-xs md:text-sm font-medium w-6 text-right">{report.in_progress_tasks}</span>
                      </div>
                    </div>
                    <div className="flex items-center justify-between gap-2">
                      <span className="text-xs md:text-sm text-gray-600 whitespace-nowrap">대기</span>
                      <div className="flex items-center gap-2 flex-1">
                        <div className="flex-1 bg-gray-200 rounded-full h-2">
                          <div
                            className="bg-gray-600 h-2 rounded-full"
                            style={{ width: `${(report.pending_tasks / report.total_tasks) * 100}%` }}
                          />
                        </div>
                        <span className="text-xs md:text-sm font-medium w-6 text-right">{report.pending_tasks}</span>
                      </div>
                    </div>
                  </div>
                </div>

                {/* 타입별 분포 */}
                <div>
                  <h4 className="text-xs md:text-sm font-medium text-gray-700 mb-2 md:mb-3">업무 타입별</h4>
                  <div className="space-y-2 md:space-y-3">
                    <div className="flex items-center justify-between gap-2">
                      <span className="text-xs md:text-sm text-gray-600 whitespace-nowrap">자체사업</span>
                      <div className="flex items-center gap-2 flex-1">
                        <div className="flex-1 bg-gray-200 rounded-full h-2">
                          <div
                            className="bg-purple-600 h-2 rounded-full"
                            style={{ width: `${(report.self_tasks / report.total_tasks) * 100}%` }}
                          />
                        </div>
                        <span className="text-xs md:text-sm font-medium w-6 text-right">{report.self_tasks}</span>
                      </div>
                    </div>
                    <div className="flex items-center justify-between gap-2">
                      <span className="text-xs md:text-sm text-gray-600 whitespace-nowrap">보조사업</span>
                      <div className="flex items-center gap-2 flex-1">
                        <div className="flex-1 bg-gray-200 rounded-full h-2">
                          <div
                            className="bg-orange-600 h-2 rounded-full"
                            style={{ width: `${(report.subsidy_tasks / report.total_tasks) * 100}%` }}
                          />
                        </div>
                        <span className="text-xs md:text-sm font-medium w-6 text-right">{report.subsidy_tasks}</span>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            {/* 완료된 업무 목록 */}
            {report.completed_task_details.length > 0 && (
              <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-4 md:p-6">
                <h3 className="text-base md:text-lg font-semibold text-gray-900 mb-3 md:mb-4 flex items-center gap-2">
                  <CheckCircle className="w-4 h-4 md:w-5 md:h-5 text-green-600" />
                  완료된 업무 ({report.completed_task_details.length}개)
                </h3>
                <div className="space-y-2 md:space-y-3">
                  {report.completed_task_details.map((task) => (
                    <div key={task.id} className="flex flex-col md:flex-row md:items-center justify-between gap-2 md:gap-3 p-3 md:p-4 bg-green-50 rounded-lg border border-green-200">
                      <div className="flex-1 min-w-0">
                        <div className="font-medium text-sm md:text-base text-gray-900 truncate">{task.title}</div>
                        <div className="text-xs md:text-sm text-gray-600 truncate">{task.business_name}</div>
                      </div>
                      <div className="flex items-center gap-2 md:gap-3 flex-wrap">
                        <span className={`px-2 py-0.5 rounded-full text-xs font-medium ${getStatusBadgeColor(task.status)}`}>
                          {task.task_type === 'self' ? '자체' : '보조'}
                        </span>
                        <span className={`text-xs md:text-sm font-medium ${getPriorityColor(task.priority)}`}>
                          {task.priority === 'high' ? '높음' : task.priority === 'medium' ? '보통' : '낮음'}
                        </span>
                        <div className="text-xs text-gray-500">
                          {formatDate(task.completed_at)}
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* 미완료 업무 목록 */}
            {report.pending_task_details.length > 0 && (
              <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-4 md:p-6">
                <h3 className="text-base md:text-lg font-semibold text-gray-900 mb-3 md:mb-4 flex items-center gap-2">
                  <Clock className="w-4 h-4 md:w-5 md:h-5 text-yellow-600" />
                  미완료 업무 ({report.pending_task_details.length}개)
                </h3>
                <div className="space-y-2 md:space-y-3">
                  {report.pending_task_details.map((task) => (
                    <div key={task.id} className={`flex flex-col md:flex-row md:items-center justify-between gap-2 md:gap-3 p-3 md:p-4 rounded-lg border ${
                      task.days_overdue && task.days_overdue > 0
                        ? 'bg-red-50 border-red-200'
                        : 'bg-yellow-50 border-yellow-200'
                    }`}>
                      <div className="flex-1 min-w-0">
                        <div className="font-medium text-sm md:text-base text-gray-900 truncate">{task.title}</div>
                        <div className="text-xs md:text-sm text-gray-600 truncate">{task.business_name}</div>
                      </div>
                      <div className="flex items-center gap-2 md:gap-3 flex-wrap">
                        <span className={`px-2 py-0.5 rounded-full text-xs font-medium ${getStatusBadgeColor(task.status)}`}>
                          {task.task_type === 'self' ? '자체' : '보조'}
                        </span>
                        <span className={`text-xs md:text-sm font-medium ${getPriorityColor(task.priority)}`}>
                          {task.priority === 'high' ? '높음' : task.priority === 'medium' ? '보통' : '낮음'}
                        </span>
                        {task.days_overdue && task.days_overdue > 0 && (
                          <span className="px-2 py-0.5 bg-red-100 text-red-800 rounded-full text-xs font-medium">
                            {task.days_overdue}일 연체
                          </span>
                        )}
                        {task.due_date && (
                          <div className="text-xs text-gray-500 whitespace-nowrap">
                            마감: {formatDate(task.due_date)}
                          </div>
                        )}
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>
        ) : (
          <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-12 text-center">
            <Calendar className="w-16 h-16 text-gray-300 mx-auto mb-4" />
            <p className="text-gray-500">주간을 선택하고 리포트 생성 버튼을 클릭하세요</p>
          </div>
        )}
      </div>
    </AdminLayout>
  )
}

// 주간 리포트는 모든 사용자가 접근 가능 (레벨 1: 일반사용자도 가능)
export default withAuth(WeeklyReportsPage, undefined, 1)